[ {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 9: Verbal",
  "Complete_ThoughtStarter_Required__c" : false,
  "Complete_RFP_Required__c" : true
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 6: Approved to Pitch",
  "Complete_ThoughtStarter_Required__c" : false,
  "Complete_RFP_Required__c" : true
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 8: Negotiations",
  "Complete_ThoughtStarter_Required__c" : false,
  "Complete_RFP_Required__c" : true
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 3: TS Pitched",
  "Complete_ThoughtStarter_Required__c" : true,
  "Complete_RFP_Required__c" : false
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 5: Business Review",
  "Complete_ThoughtStarter_Required__c" : false,
  "Complete_RFP_Required__c" : true
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 7: Pitched",
  "Complete_ThoughtStarter_Required__c" : false,
  "Complete_RFP_Required__c" : true
}, {
  "attributes" : {
    "type" : "Stage_Requires_Complete_TS_RFP__c"
  },
  "Name" : "Stage 2: TS Approved to Pitch",
  "Complete_ThoughtStarter_Required__c" : true,
  "Complete_RFP_Required__c" : false
} ]